name: test

on:
  push:
    branches:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        python:
          - "3.10"
          - "3.13"
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}

      - name: install apt packages
        # pycurl build requirements
        run: |
          sudo apt-get update && sudo apt-get -y install \
              libcurl4-gnutls-dev \
              libgnutls28-dev \
              libmemcached-dev

      - name: install
        run: |
          python3 -m pip install -r requirements.in -r requirements-dev.txt
          python3 -m pip install -v -e .
      - name: install mypy
        run: |
          python3 -m pip install mypy types-pycurl types-requests types-Markdown pyflakes
      - name: run mypy
        run: |
          mypy nbviewer
      - name: run pyflakes
        run: |
          pyflakes nbviewer

      - name: pip freeze
        run: |
          python3 -m pip freeze

      - name: run tests
        run: |
          pytest -v nbviewer/tests -s
